repo: 'header-icons'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - google-fonts
  - box-sizing
  - body-margin-0

html:
  - path: "index.html"
    outline: false
    has:
      - ['link[href*="Merriweather"]', 'The Google Font, `Merriweather` is missing']
      - 'header'
      - 'header h1'
      - 'header img'
      - 'header nav'
      - 'header ul'
      - 'header a'
      - 'img[src*="grain-left.svg"]'
      - 'img[src*="grain-right.svg"]'
    search:
      - 'Grains'
      - 'Home'
      - 'Cereals'
      - 'Legumes'

css:
  - path: 'css/main.css'
    search:
      - '#d05c2e'
      - '#a63f38'
      - 'display: flex'
      - 'justify-content:'
      - 'align-items:'

screenshots:
  - path: 'index.html'
    label: 'Before'
    sizes: [320, 650]
  - path: 'index.html'
    label: 'After'
    sizes: [650]
    before: |
      hover('nav li:nth-child(2) a', done);

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('nav a');
        let oldBg = css(link).backgroundColor;

        hover(link, function () {
          if (css(link).backgroundColor == oldBg) return fail('The background colour of the navigaiton links don’t change when hovered')
          pass();
        });
